trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              options: '-B'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              publishJUnitResults: true
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'

  - stage: Test
    jobs:
      - job: RegressionTests
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              options: '-Dtest=**RegressionTestSuite'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              publishJUnitResults: true
              testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
